# Generated by Django 3.2.8 on 2021-10-31 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
            },
        ),
        migrations.CreateModel(
            name='Cleaner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(default='Cleaner', max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 920197))),
            ],
        ),
        migrations.CreateModel(
            name='Defrost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(default='defrost', max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 921195))),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(default='fridge', max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 921195))),
            ],
        ),
        migrations.CreateModel(
            name='Notebooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('diag', models.IntegerField(verbose_name='Диагональ экрана')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(default='notebooks', max_length=100, verbose_name='Категория')),
                ('CPU', models.CharField(max_length=100, verbose_name='Процессор')),
                ('GPU', models.CharField(max_length=100, verbose_name='Процессор')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 921195))),
            ],
        ),
        migrations.CreateModel(
            name='Smartphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('diag', models.IntegerField(verbose_name='Диагональ экрана')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('SIM', models.IntegerField(verbose_name='Кол-во симкарт')),
                ('category', models.CharField(default='smartphones', max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 919200))),
            ],
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('diag', models.IntegerField(verbose_name='Диагональ экрана')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(default='Television', max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 919200))),
            ],
        ),
        migrations.CreateModel(
            name='Washing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена товара')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
                ('brand', models.CharField(max_length=100, verbose_name='Производитель')),
                ('category', models.CharField(default='washing', max_length=100, verbose_name='Категория')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2021, 10, 31, 19, 33, 49, 922192))),
            ],
        ),
    ]
