# Generated by Django 3.2.8 on 2021-11-01 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaner',
            options={'verbose_name': 'Пылесос', 'verbose_name_plural': 'Пылесосы'},
        ),
        migrations.AlterModelOptions(
            name='defrost',
            options={'verbose_name': 'Микроволновка', 'verbose_name_plural': 'Микроволновки'},
        ),
        migrations.AlterModelOptions(
            name='fridge',
            options={'verbose_name': 'Холодильник', 'verbose_name_plural': 'Холодильники'},
        ),
        migrations.AlterModelOptions(
            name='notebooks',
            options={'verbose_name': 'Ноутбук', 'verbose_name_plural': 'Ноутбуки'},
        ),
        migrations.AlterModelOptions(
            name='smartphones',
            options={'verbose_name': 'Смартфон', 'verbose_name_plural': 'Смартфоны'},
        ),
        migrations.AlterModelOptions(
            name='television',
            options={'verbose_name': 'Телевизор', 'verbose_name_plural': 'Телевизоры'},
        ),
        migrations.AlterModelOptions(
            name='washing',
            options={'verbose_name': 'Стиральная машина', 'verbose_name_plural': 'Стиральные машины'},
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 276095)),
        ),
        migrations.AlterField(
            model_name='defrost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 277093)),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 276095)),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 276095)),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 275098)),
        ),
        migrations.AlterField(
            model_name='television',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 275098)),
        ),
        migrations.AlterField(
            model_name='washing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 14, 8, 2, 277093)),
        ),
    ]
