# Generated by Django 3.2.8 on 2021-11-01 13:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0002_auto_20211101_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('url', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='cleaner',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 346830)),
        ),
        migrations.AlterField(
            model_name='defrost',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 347828)),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 346830)),
        ),
        migrations.AlterField(
            model_name='notebooks',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 346830)),
        ),
        migrations.AlterField(
            model_name='smartphones',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 345832)),
        ),
        migrations.AlterField(
            model_name='television',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 345832)),
        ),
        migrations.AlterField(
            model_name='washing',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 16, 32, 49, 347828)),
        ),
    ]
